import {Dimensions, Platform} from 'react-native';

let BOTTOM_BAR_HEIGHT = 50;
let BOTTOM_BUFFER_HEIGHT = 24;
let TOP_MARGIN_HEIGHT = 0;
if (Platform.OS === 'ios') {
  BOTTOM_BUFFER_HEIGHT = 0;
  TOP_MARGIN_HEIGHT = 20;
}
let WINDOW_HEIGHT = Dimensions.get('window').height;
let WINDOW_WIDTH = Dimensions.get('window').width;

let BOTTOM_BUTTON_WIDTH = (WINDOW_WIDTH - 10) / 5;

module.exports = {
  ACTION: {
    CHANGE_PAGE: 'CHANGE_PAGE',
    CHANGE_PAGE_BACK: 'CHANGE_PAGE_BACK',
    SET_ASK_PAGE_TO_SET_CURRENT_SUBPAGE_ID:
      'SET_ASK_PAGE_TO_SET_CURRENT_SUBPAGE_ID',
    SET_BACK_ANDROID: 'SET_BACK_ANDROID',
    SET_BACK_SUBPAGE: 'SET_BACK_SUBPAGE',
    SET_BACK_PAGE: 'SET_BACK_PAGE',
    SET_CURRENT_SUBPAGE_ID: 'SET_CURRENT_SUBPAGE_ID',
    SET_EXIT_FULLSCREEN: 'SET_EXIT_FULLSCREEN',
    SET_HIDE_FULLSCREEN: 'SET_HIDE_FULLSCREEN',
    SET_NEXT_SUBPAGE: 'SET_NEXT_SUBPAGE',
    SET_NEXT_SUBPAGE_DONE: 'SET_NEXT_SUBPAGE_DONE',
    SET_PRESS_SAME_BUTTON: 'SET_PRESS_SAME_BUTTON',
    SET_SUBPAGE_SCROLL_TOP: 'SET_SUBPAGE_SCROLL_TOP',
  },
  DIMENSION: {
    BOTTOM_BAR_HEIGHT,
    BOTTOM_BUFFER_HEIGHT,
    BOTTOM_BUTTON_WIDTH,
    CONTENT_HEIGHT: WINDOW_HEIGHT - TOP_MARGIN_HEIGHT - BOTTOM_BAR_HEIGHT
      - BOTTOM_BUFFER_HEIGHT,
    FULLSCREEN_CONTENT_HEIGHT: WINDOW_HEIGHT - TOP_MARGIN_HEIGHT
      - BOTTOM_BUFFER_HEIGHT,
    TOP_MARGIN_HEIGHT,
    WINDOW_HEIGHT,
    WINDOW_WIDTH,
  },
  PAGE: {
    ADD: 'ADD',
    FULLSCREEN: 'FULLSCREEN',
    HOME: 'HOME',
    LOVE: 'LOVE',
    PROFILE: 'PROFILE',
    SEARCH: 'SEARCH',
  },
  SUBPAGE: {
    SPFullScreen: 'SPFullScreen',
    SPHome: 'SPHome',
    SPLove: 'SPLove',
    SPProfile: 'SPProfile',
    SPSearch: 'SPSearch',
  },
  STYLE: {
    BOTTOM_BUTTON_STYLE: {height:BOTTOM_BAR_HEIGHT, width:BOTTOM_BUTTON_WIDTH,
      alignItems:'center', justifyContent:'center'},
    BOTTOM_BUTTON_IMAGE_STYLE: {width:30, height:30},
  }
}
